### ISSUE TITLE
Sending Message... nothing received

### ISSUE THREAD

**Issue by padan123** [dev-fatal/queue-notify#2]
Hi,

Thanks for this program! I've followed with the instructions however, and while i get python to be 'monitoring', then 'sending message' when my queue pops... i don't actually receive anything in Telegram. I'm very new to Telegram and Python so it may be something simple i'm missing.  One thing i did do which wasn't mention  was entering my bot username under 'chat_id'.

Any help would be appreciated, thanks!
Michael

**Comment by dev-fatal** [comment]
>One thing i did do which wasn't mention was entering my bot username under 'chat_id'.

Don't do that. Follow the instructions

**Comment by padan123** [comment]
I've put 'chat_id' back to blank, still the same thing - cmd prompt shows 'sending message...', yet nothing is received. Am i meant to be installing Telegram on my phone or my PC?
