### ISSUE TITLE
console window closes after sending bot test message

### ISSUE THREAD

**Issue by Spizglub** [dev-fatal/queue-notify#5]
Hey, thanks for your work on this :)

I'm on win11 and Python 3.10.11.

I will run 'main' send a test message to the telegram bot then hit enter in the console. The console will generate chat_id as I can see it saved to the config TOML file. However as soon as I hit enter, the console closes.

Trying to re-open the console means it closes immediately.

Restarted and removed the 'chat_id =' field. As soon as I hit enter on the console the same situation begins again. Any ideas?

**Comment by dev-fatal** [comment]
When you say you’re running main, do you mean you’re typing `python main.py` as shown in the instructions, or are you double clicking the python file from File Explorer?

And when you remove the `chat_id` field, do you mean that you are replacing the value with an empty string?

**Comment by Spizglub** [comment]
My bad, file explorer - should be good now cheers, showing 'monitoring...' in cmd. I was misunderstanding.

By  'Run the program (from inside the directory, as before) with python main.py.' I misunderstood as from inside file explorer.

Yeah was returning it to a blank entry in chat_id = "***" 
so just the quotation marks

**Comment by dev-fatal** [comment]
Please close the issue if it’s resolved, thanks
